#ifndef NIGMA_CAOL_SPECIFICS_VALUES_ARCHITECTURE_H
#define NIGMA_CAOL_SPECIFICS_VALUES_ARCHITECTURE_H

#define NCAOL_SPECS_ARCH_VAL_CLASS_RISC 0
#define NCAOL_SPECS_ARCH_VAL_CLASS_EPIC 1
#define NCAOL_SPECS_ARCH_VAL_CLASS_CISC 2

#define NCAOL_SPECS_ARCH_VAL_TYPE_Alpha             0
#define NCAOL_SPECS_ARCH_VAL_TYPE_ARM               1
#define NCAOL_SPECS_ARCH_VAL_TYPE_ARM_Thumb         2
#define NCAOL_SPECS_ARCH_VAL_TYPE_ARM64             3
#define NCAOL_SPECS_ARCH_VAL_TYPE_Blackfin          4
#define NCAOL_SPECS_ARCH_VAL_TYPE_MIPS              5
#define NCAOL_SPECS_ARCH_VAL_TYPE_PowerPC           6
#define NCAOL_SPECS_ARCH_VAL_TYPE_RS6000            7
#define NCAOL_SPECS_ARCH_VAL_TYPE_SPARC             8
#define NCAOL_SPECS_ARCH_VAL_TYPE_SuperH            9
#define NCAOL_SPECS_ARCH_VAL_TYPE_IntelItanium_IA64 10
#define NCAOL_SPECS_ARCH_VAL_TYPE_x86_64            11
#define NCAOL_SPECS_ARCH_VAL_TYPE_Intel_x86         12
#define NCAOL_SPECS_ARCH_VAL_TYPE_Intel_x86_16Bit   13
#define NCAOL_SPECS_ARCH_VAL_TYPE_Motorola68k       14
#define NCAOL_SPECS_ARCH_VAL_TYPE_SystemZ           15

#endif