#ifndef NIGMA_CAOL_SPECIFICS_VALUES_CSTANDARD_H
#define NIGMA_CAOL_SPECIFICS_VALUES_CSTANDARD_H

#define NCAOL_SPECS_CSTD_VAL_ID_C89C90 0
#define NCAOL_SPECS_CSTD_VAL_ID_C94C95 1
#define NCAOL_SPECS_CSTD_VAL_ID_C99    2
#define NCAOL_SPECS_CSTD_VAL_ID_C11    3
#define NCAOL_SPECS_CSTD_VAL_ID_C17C18 4
#define NCAOL_SPECS_CSTD_VAL_ID_C23    5

#define NCAOL_SPECS_CSTD_VAL_NAME_C89C90 "C89(K&R) / C90(ANSI-C)"
#define NCAOL_SPECS_CSTD_VAL_NAME_C94C95 "C94 / C95"
#define NCAOL_SPECS_CSTD_VAL_NAME_C99    "C99"
#define NCAOL_SPECS_CSTD_VAL_NAME_C11    "C11"
#define NCAOL_SPECS_CSTD_VAL_NAME_C17C18 "C17 / C18"
#define NCAOL_SPECS_CSTD_VAL_NAME_C23    "C23"

#endif