#ifndef NIGMA_CAOL_SPECIFICS_VALUES_CSTDLIBRARY_H
#define NIGMA_CAOL_SPECIFICS_VALUES_CSTDLIBRARY_H

#define NCAOL_SPECS_CSTDLIB_VAL_ID_Bare    0
#define NCAOL_SPECS_CSTDLIB_VAL_ID_Bionic  1
#define NCAOL_SPECS_CSTDLIB_VAL_ID_glibc   2
#define NCAOL_SPECS_CSTDLIB_VAL_ID_klibc   3
#define NCAOL_SPECS_CSTDLIB_VAL_ID_uClibc  4
#define NCAOL_SPECS_CSTDLIB_VAL_ID_zOSlib  5
#define NCAOL_SPECS_CSTDLIB_VAL_ID_WINDOWS 6

#define NCAOL_SPECS_CSTDLIB_VAL_NAME_Bare    "Bare, no utilized C standard library"
#define NCAOL_SPECS_CSTDLIB_VAL_NAME_Bionic  "Bionic"
#define NCAOL_SPECS_CSTDLIB_VAL_NAME_glibc   "glibc"
#define NCAOL_SPECS_CSTDLIB_VAL_NAME_klibc   "klibc"
#define NCAOL_SPECS_CSTDLIB_VAL_NAME_uClibc  "uClibc"
#define NCAOL_SPECS_CSTDLIB_VAL_NAME_zOSlib  "zOSlib"
#define NCAOL_SPECS_CSTDLIB_VAL_NAME_WINDOWS "WINDOWS"

#endif