#ifndef NIGMA_CAOL_SPECIFICS_ID_CSTANDARD_H
#define NIGMA_CAOL_SPECIFICS_ID_CSTANDARD_H


#include "values/cstandard.h"

/*Standard-Specific identifications:
C89(K&R)/C90(ANSI-C):
    __STDC__
        [UNDEFINED]
C94/C95:
    __STDC_VERSION__
        199409L
C99:
    __STDC_VERSION__
        199901L
C11:
    __STDC_VERSION__
        201112L
C17/C18:
    __STDC_VERSION__
        201710L
C23:
    __STDC_VERSION__
        202311L
*/
#if defined(__STDC_VERSION__)
    #if (__STDC_VERSION__ == 199409L)
        #define NCAOL_SPECS_CSTD_DEF_STD_NAME NCAOL_SPECS_CSTD_VAL_NAME_C94C95
        #define NCAOL_SPECS_CSTD_DEF_STD_ID NCAOL_SPECS_CSTD_VAL_ID_C94C95
    #elif (__STDC_VERSION__ == 199901L)
        #define NCAOL_SPECS_CSTD_DEF_STD_NAME NCAOL_SPECS_CSTD_VAL_NAME_C99
        #define NCAOL_SPECS_CSTD_DEF_STD_ID NCAOL_SPECS_CSTD_VAL_ID_C99
    #elif (__STDC_VERSION__ == 201112L)
        #define NCAOL_SPECS_CSTD_DEF_STD_NAME NCAOL_SPECS_CSTD_VAL_NAME_C11
        #define NCAOL_SPECS_CSTD_DEF_STD_ID NCAOL_SPECS_CSTD_VAL_ID_C11
    #elif (__STDC_VERSION__ == 201710L)
        #define NCAOL_SPECS_CSTD_DEF_STD_NAME NCAOL_SPECS_CSTD_VAL_NAME_C17C18
        #define NCAOL_SPECS_CSTD_DEF_STD_ID NCAOL_SPECS_CSTD_VAL_ID_C17C18
    #elif (__STDC_VERSION__ == 202311L)
        #define NCAOL_SPECS_CSTD_DEF_STD_NAME NCAOL_SPECS_CSTD_VAL_NAME_C23
        #define NCAOL_SPECS_CSTD_DEF_STD_ID NCAOL_SPECS_CSTD_VAL_ID_C23
    #endif
#elif defined(__STDC__)
    #define NCAOL_SPECS_CSTD_DEF_STD_NAME NCAOL_SPECS_CSTD_VAL_NAME_C89C90
    #define NCAOL_SPECS_CSTD_DEF_STD_ID NCAOL_SPECS_CSTD_VAL_ID_C89C90
#endif


#endif
