#ifndef NIGMA_CAOL_SPECIFICS_ID_CSTDLIBRARY_H
#define NIGMA_CAOL_SPECIFICS_ID_CSTDLIBRARY_H


#include "values/cstdlibrary.h"

/*C-Standard Library-Specific identifications:
Bare:
    Upon every other identifier bellow being nonexistent; ((defined(...) || ...) == 0)

Bionic:
    __BIONIC__

GNU glibc:
    Prior Version 6:
        __GNU_LIBRARY__
        __GNU_LIBRARY_MINOR__
    Version 6:
        __GLIBC__
        __GLIBC_MINOR__

klibc:
    __KLIBC__

uClibc:
    __UCLIBC__

z/OS libc:
    Host:
        __LIBREL__
    Target:
        __TARGET_LIB__

WINDOWS:
    Not actual Library for MSVCRT or UCRT,
    but Micrsoft is so terrible with Documentation,
    that I do not give a frick after 5 *HOURS*..
*/


//Generic and Explicit identifications:
#if (defined(NCAOL_ENABLES_EXPLICIT_CSTDLIB_TYPE) == 0)
    #if defined(__BIONIC__)
        #define NCAOL_ENABLES_EXPLICIT_CSTDLIB_TYPE NCAOL_SPECS_CSTDLIB_VAL_ID_Bionic
    #elif (defined(__GNU_LIBRARY__) || defined(__GLIBC__))
        #define NCAOL_ENABLES_EXPLICIT_CSTDLIB_TYPE NCAOL_SPECS_CSTDLIB_VAL_ID_glibc
    #elif defined(__KLIBC__)
        #define NCAOL_ENABLES_EXPLICIT_CSTDLIB_TYPE NCAOL_SPECS_CSTDLIB_VAL_ID_klibc
    #elif defined(__UCLIBC__)
        #define NCAOL_ENABLES_EXPLICIT_CSTDLIB_TYPE NCAOL_SPECS_CSTDLIB_VAL_ID_uClibc
    #elif (defined(__LIBREL__) || defined(__TARGET_LIB__))
        #define NCAOL_ENABLES_EXPLICIT_CSTDLIB_TYPE NCAOL_SPECS_CSTDLIB_VAL_ID_zOSlib
    #endif
#endif

#if defined(NCAOL_ENABLES_EXPLICIT_CSTDLIB_TYPE)
    #if (NCAOL_ENABLES_EXPLICIT_CSTDLIB_TYPE == NCAOL_SPECS_CSTDLIB_VAL_ID_Bare)
        #define NCAOL_SPECS_CSTDLIB_DEF_LIB_NAME NCAOL_SPECS_CSTDLIB_VAL_NAME_Bare
        #define NCAOL_SPECS_CSTDLIB_DEF_LIB_ID NCAOL_SPECS_CSTDLIB_VAL_ID_Bare
    #elif (NCAOL_ENABLES_EXPLICIT_CSTDLIB_TYPE == NCAOL_SPECS_CSTDLIB_VAL_ID_Bionic)
        #define NCAOL_SPECS_CSTDLIB_DEF_LIB_NAME NCAOL_SPECS_CSTDLIB_VAL_NAME_Bionic
        #define NCAOL_SPECS_CSTDLIB_DEF_LIB_ID NCAOL_SPECS_CSTDLIB_VAL_ID_Bionic
    #elif (NCAOL_ENABLES_EXPLICIT_CSTDLIB_TYPE == NCAOL_SPECS_CSTDLIB_VAL_ID_glibc)
        #define NCAOL_SPECS_CSTDLIB_DEF_LIB_NAME NCAOL_SPECS_CSTDLIB_VAL_NAME_glibc
        #define NCAOL_SPECS_CSTDLIB_DEF_LIB_ID NCAOL_SPECS_CSTDLIB_VAL_ID_glibc
    #elif (NCAOL_ENABLES_EXPLICIT_CSTDLIB_TYPE == NCAOL_SPECS_CSTDLIB_VAL_ID_klibc)
        #define NCAOL_SPECS_CSTDLIB_DEF_LIB_NAME NCAOL_SPECS_CSTDLIB_VAL_NAME_klibc
        #define NCAOL_SPECS_CSTDLIB_DEF_LIB_ID NCAOL_SPECS_CSTDLIB_VAL_ID_klibc
    #elif (NCAOL_ENABLES_EXPLICIT_CSTDLIB_TYPE == NCAOL_SPECS_CSTDLIB_VAL_ID_uClibc)
        #define NCAOL_SPECS_CSTDLIB_DEF_LIB_NAME NCAOL_SPECS_CSTDLIB_VAL_NAME_uClibc
        #define NCAOL_SPECS_CSTDLIB_DEF_LIB_ID NCAOL_SPECS_CSTDLIB_VAL_ID_uClibc
    #elif (NCAOL_ENABLES_EXPLICIT_CSTDLIB_TYPE == NCAOL_SPECS_CSTDLIB_VAL_ID_zOSlib)
        #define NCAOL_SPECS_CSTDLIB_DEF_LIB_NAME NCAOL_SPECS_CSTDLIB_VAL_NAME_zOSlib
        #define NCAOL_SPECS_CSTDLIB_DEF_LIB_ID NCAOL_SPECS_CSTDLIB_VAL_ID_zOSlib
    #elif (NCAOL_ENABLES_EXPLICIT_CSTDLIB_TYPE == NCAOL_SPECS_CSTDLIB_VAL_ID_WINDOWS)
        #define NCAOL_SPECS_CSTDLIB_DEF_LIB_NAME NCAOL_SPECS_CSTDLIB_VAL_NAME_WINDOWS
        #define NCAOL_SPECS_CSTDLIB_DEF_LIB_ID NCAOL_SPECS_CSTDLIB_VAL_ID_WINDOWS
    #endif
#endif


#endif