#ifndef NIGMA_CAOL_SPECIFICS_ARCHITECTURE_H
#define NIGMA_CAOL_SPECIFICS_ARCHITECTURE_H


#include "OS.h"
#include "ID/architecture.h"

#if defined(NCAOL_SPECS_ARCH_DEF_ARCH_ID)
    #if (NCAOL_SPECS_ARCH_DEF_ARCH_ID == NCAOL_SPECS_ARCH_VAL_ID_Alpha)
    #elif (NCAOL_SPECS_ARCH_DEF_ARCH_ID == NCAOL_SPECS_ARCH_VAL_ID_ARM)
    #elif (NCAOL_SPECS_ARCH_DEF_ARCH_ID == NCAOL_SPECS_ARCH_VAL_ID_ARM_Thumb)
    #elif (NCAOL_SPECS_ARCH_DEF_ARCH_ID == NCAOL_SPECS_ARCH_VAL_ID_ARM64)
    #elif (NCAOL_SPECS_ARCH_DEF_ARCH_ID == NCAOL_SPECS_ARCH_VAL_ID_Blackfin)
    #elif (NCAOL_SPECS_ARCH_DEF_ARCH_ID == NCAOL_SPECS_ARCH_VAL_ID_MIPS)
    #elif (NCAOL_SPECS_ARCH_DEF_ARCH_ID == NCAOL_SPECS_ARCH_VAL_ID_PowerPC)
    #elif (NCAOL_SPECS_ARCH_DEF_ARCH_ID == NCAOL_SPECS_ARCH_VAL_ID_PowerPC64)
    #elif (NCAOL_SPECS_ARCH_DEF_ARCH_ID == NCAOL_SPECS_ARCH_VAL_ID_RS6000)
    #elif (NCAOL_SPECS_ARCH_DEF_ARCH_ID == NCAOL_SPECS_ARCH_VAL_ID_SPARC)
    #elif (NCAOL_SPECS_ARCH_DEF_ARCH_ID == NCAOL_SPECS_ARCH_VAL_ID_SuperH)
    #elif (NCAOL_SPECS_ARCH_DEF_ARCH_ID == NCAOL_SPECS_ARCH_VAL_ID_IntelItanium_IA64)
    #elif (NCAOL_SPECS_ARCH_DEF_ARCH_ID == NCAOL_SPECS_ARCH_VAL_ID_x86_64)
    #elif (NCAOL_SPECS_ARCH_DEF_ARCH_ID == NCAOL_SPECS_ARCH_VAL_ID_Intel_x86)
    #elif (NCAOL_SPECS_ARCH_DEF_ARCH_ID == NCAOL_SPECS_ARCH_VAL_ID_Intel_x86_16Bit)
    #elif (NCAOL_SPECS_ARCH_DEF_ARCH_ID == NCAOL_SPECS_ARCH_VAL_ID_Motorola68k)
    #elif (NCAOL_SPECS_ARCH_DEF_ARCH_ID == NCAOL_SPECS_ARCH_VAL_ID_SystemZ)
    #endif
#else
    #error "nCAOL: Apologizes, but it seems like the utilized Architecture is unsupported! - But please do feel free to send a request, if you have the spare time."
#endif


#endif
