#ifndef NIGMA_CAOL_SPECIFICS_CSTANDARD_H
#define NIGMA_CAOL_SPECIFICS_CSTANDARD_H


#include "values/cstandard.h"

/*Standard-Specific identifications:
C89(K&R)/C90(ANSI-C):
    __STDC__
        [UNDEFINED]
C94/C95:
    __STDC_VERSION__
        199409L
C99:
    __STDC_VERSION__
        199901L
C11:
    __STDC_VERSION__
        201112L
C17/C18:
    __STDC_VERSION__
        201710L
C23:
    __STDC_VERSION__
        202311L
*/
#if defined(__STDC_VERSION__)
    #if (__STDC_VERSION__ == 199409L)
        #define NCAOL_SPECS_CSTD_DEF_STD_NAME NCAOL_SPECS_CSTD_VAL_NAME_C94C95
        #define NCAOL_SPECS_CSTD_DEF_STD_ID NCAOL_SPECS_CSTD_VAL_ID_C94C95
    #elif (__STDC_VERSION__ == 199901L)
        #define NCAOL_SPECS_CSTD_DEF_STD_NAME NCAOL_SPECS_CSTD_VAL_NAME_C99
        #define NCAOL_SPECS_CSTD_DEF_STD_ID NCAOL_SPECS_CSTD_VAL_ID_C99
    #elif (__STDC_VERSION__ == 201112L)
        #define NCAOL_SPECS_CSTD_DEF_STD_NAME NCAOL_SPECS_CSTD_VAL_NAME_C11
        #define NCAOL_SPECS_CSTD_DEF_STD_ID NCAOL_SPECS_CSTD_VAL_ID_C11
    #elif (__STDC_VERSION__ == 201710L)
        #define NCAOL_SPECS_CSTD_DEF_STD_NAME NCAOL_SPECS_CSTD_VAL_NAME_C17C18
        #define NCAOL_SPECS_CSTD_DEF_STD_ID NCAOL_SPECS_CSTD_VAL_ID_C17C18
    #elif (__STDC_VERSION__ == 202311L)
        #define NCAOL_SPECS_CSTD_DEF_STD_NAME NCAOL_SPECS_CSTD_VAL_NAME_C23
        #define NCAOL_SPECS_CSTD_DEF_STD_ID NCAOL_SPECS_CSTD_VAL_ID_C23
    #else
        #error "nCAOL: Apologizes, but it seems like the utilized standard is unsupported!.."
    #endif
#else
    #if defined(__STDC__)
        #define NCAOL_SPECS_CSTD_DEF_STD_NAME NCAOL_SPECS_CSTD_VAL_NAME_C89C90
        #define NCAOL_SPECS_CSTD_DEF_STD_ID NCAOL_SPECS_CSTD_VAL_ID_C89C90
    #else
        #error "nCAOL: Apologizes, but it seems like the utilized standard is unsupported! - Somehow one before C94/C95 that isn't C89(K&R)/C90(ANSI-C)?.."
    #endif
#endif

#define caolSpecsCSTD(t, ...) NCAOL_SPECS_CSTD_INTER_##t(__VA_ARGS__)
#define NCAOL_SPECS_CSTD_INTER_STD(t, ...) NCAOL_SPECS_CSTD_INTER_STD_##t(__VA_ARGS__)
#define NCAOL_SPECS_CSTD_INTER_STD_NAME(t) NCAOL_SPECS_CSTD_INTER_STD_NAME_##t
#define NCAOL_SPECS_CSTD_INTER_STD_ID(t)   NCAOL_SPECS_CSTD_INTER_STD_ID_##t

#define NCAOL_SPECS_CSTD_INTER_STD_NAME_C89 NCAOL_SPECS_CSTD_VAL_NAME_C89C90
#define NCAOL_SPECS_CSTD_INTER_STD_NAME_C90 NCAOL_SPECS_CSTD_VAL_NAME_C89C90
#define NCAOL_SPECS_CSTD_INTER_STD_NAME_C94 NCAOL_SPECS_CSTD_VAL_NAME_C94C95
#define NCAOL_SPECS_CSTD_INTER_STD_NAME_C95 NCAOL_SPECS_CSTD_VAL_NAME_C94C95
#define NCAOL_SPECS_CSTD_INTER_STD_NAME_C99 NCAOL_SPECS_CSTD_VAL_NAME_C99
#define NCAOL_SPECS_CSTD_INTER_STD_NAME_C11 NCAOL_SPECS_CSTD_VAL_NAME_C11
#define NCAOL_SPECS_CSTD_INTER_STD_NAME_C17 NCAOL_SPECS_CSTD_VAL_NAME_C17C18
#define NCAOL_SPECS_CSTD_INTER_STD_NAME_C18 NCAOL_SPECS_CSTD_VAL_NAME_C17C18
#define NCAOL_SPECS_CSTD_INTER_STD_NAME_C23 NCAOL_SPECS_CSTD_VAL_NAME_C23
#define NCAOL_SPECS_CSTD_INTER_STD_NAME_TOP NCAOL_SPECS_CSTD_VAL_NAME_C23

#define NCAOL_SPECS_CSTD_INTER_STD_ID_C89 NCAOL_SPECS_CSTD_VAL_ID_C89C90
#define NCAOL_SPECS_CSTD_INTER_STD_ID_C90 NCAOL_SPECS_CSTD_VAL_ID_C89C90
#define NCAOL_SPECS_CSTD_INTER_STD_ID_C94 NCAOL_SPECS_CSTD_VAL_ID_C94C95
#define NCAOL_SPECS_CSTD_INTER_STD_ID_C95 NCAOL_SPECS_CSTD_VAL_ID_C94C95
#define NCAOL_SPECS_CSTD_INTER_STD_ID_C99 NCAOL_SPECS_CSTD_VAL_ID_C99
#define NCAOL_SPECS_CSTD_INTER_STD_ID_C11 NCAOL_SPECS_CSTD_VAL_ID_C11
#define NCAOL_SPECS_CSTD_INTER_STD_ID_C17 NCAOL_SPECS_CSTD_VAL_ID_C17C18
#define NCAOL_SPECS_CSTD_INTER_STD_ID_C18 NCAOL_SPECS_CSTD_VAL_ID_C17C18
#define NCAOL_SPECS_CSTD_INTER_STD_ID_C23 NCAOL_SPECS_CSTD_VAL_ID_C23
#define NCAOL_SPECS_CSTD_INTER_STD_ID_TOP NCAOL_SPECS_CSTD_VAL_ID_C23


#define NCAOL_SPECS_CSTD_INTER_CURRENT(t, ...) NCAOL_SPECS_CSTD_INTER_CURRENT_##t(__VA_ARGS__)
#define NCAOL_SPECS_CSTD_INTER_CURRENT_STD(t) NCAOL_SPECS_CSTD_INTER_CURRENT_STD_##t
#define NCAOL_SPECS_CSTD_INTER_CURRENT_STD_NAME NCAOL_SPECS_CSTD_DEF_STD_NAME
#define NCAOL_SPECS_CSTD_INTER_CURRENT_STD_ID   NCAOL_SPECS_CSTD_DEF_STD_ID


#endif