#ifndef NIGMA_CAOL_SPECIFICS_INTERFACES_H
#define NIGMA_CAOL_SPECIFICS_INTERFACES_H


#include "architecture.h"

//cstandard.h
#define caolSpecsCSTD(NCAOLarg) NCAOL_SPECS_CSTD_INTER_##NCAOLarg
#define NCAOL_SPECS_CSTD_INTER_NCAOL_STD_NAME_C89 NCAOL_SPECS_CSTD_VAL_NAME_C89
#define NCAOL_SPECS_CSTD_INTER_NCAOL_STD_NAME_C90 NCAOL_SPECS_CSTD_VAL_NAME_C90
#define NCAOL_SPECS_CSTD_INTER_NCAOL_STD_NAME_C94 NCAOL_SPECS_CSTD_VAL_NAME_C94
#define NCAOL_SPECS_CSTD_INTER_NCAOL_STD_NAME_C95 NCAOL_SPECS_CSTD_VAL_NAME_C95
#define NCAOL_SPECS_CSTD_INTER_NCAOL_STD_NAME_C99 NCAOL_SPECS_CSTD_VAL_NAME_C99
#define NCAOL_SPECS_CSTD_INTER_NCAOL_STD_NAME_C11 NCAOL_SPECS_CSTD_VAL_NAME_C11
#define NCAOL_SPECS_CSTD_INTER_NCAOL_STD_NAME_C17 NCAOL_SPECS_CSTD_VAL_NAME_C17
#define NCAOL_SPECS_CSTD_INTER_NCAOL_STD_NAME_C18 NCAOL_SPECS_CSTD_VAL_NAME_C18
#define NCAOL_SPECS_CSTD_INTER_NCAOL_STD_NAME_C23 NCAOL_SPECS_CSTD_VAL_NAME_C23
#define NCAOL_SPECS_CSTD_INTER_NCAOL_STD_NAME_TOP NCAOL_SPECS_CSTD_VAL_NAME_C23

#define NCAOL_SPECS_CSTD_INTER_NCAOL_STD_ID_C89 NCAOL_SPECS_CSTD_VAL_ID_C89
#define NCAOL_SPECS_CSTD_INTER_NCAOL_STD_ID_C90 NCAOL_SPECS_CSTD_VAL_ID_C90
#define NCAOL_SPECS_CSTD_INTER_NCAOL_STD_ID_C94 NCAOL_SPECS_CSTD_VAL_ID_C94
#define NCAOL_SPECS_CSTD_INTER_NCAOL_STD_ID_C95 NCAOL_SPECS_CSTD_VAL_ID_C95
#define NCAOL_SPECS_CSTD_INTER_NCAOL_STD_ID_C99 NCAOL_SPECS_CSTD_VAL_ID_C99
#define NCAOL_SPECS_CSTD_INTER_NCAOL_STD_ID_C11 NCAOL_SPECS_CSTD_VAL_ID_C11
#define NCAOL_SPECS_CSTD_INTER_NCAOL_STD_ID_C17 NCAOL_SPECS_CSTD_VAL_ID_C17
#define NCAOL_SPECS_CSTD_INTER_NCAOL_STD_ID_C18 NCAOL_SPECS_CSTD_VAL_ID_C18
#define NCAOL_SPECS_CSTD_INTER_NCAOL_STD_ID_C23 NCAOL_SPECS_CSTD_VAL_ID_C23
#define NCAOL_SPECS_CSTD_INTER_NCAOL_STD_ID_TOP NCAOL_SPECS_CSTD_VAL_ID_C23


#define NCAOL_SPECS_CSTD_INTER_NCAOL_CURRENT_STD_NAME NCAOL_SPECS_CSTD_DEF_STD_NAME
#define NCAOL_SPECS_CSTD_INTER_NCAOL_CURRENT_STD_ID   NCAOL_SPECS_CSTD_DEF_STD_ID



//compiler.h
#define caolSpecsComp(NCAOLarg) NCAOL_SPECS_COMP_INTER_##NCAOLarg
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_SUBJECT_FPGA    NCAOL_SPECS_COMP_VAL_SUBJECT_FPGA
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_SUBJECT_ARM     NCAOL_SPECS_COMP_VAL_SUBJECT_ARM
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_SUBJECT_RiscV   NCAOL_SPECS_COMP_VAL_SUBJECT_RiscV
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_SUBJECT_Generic NCAOL_SPECS_COMP_VAL_SUBJECT_Generic

#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_DOMAIN_Altium             NCAOL_SPECS_COMP_VAL_DOMAIN_Altium
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_DOMAIN_KEIL               NCAOL_SPECS_COMP_VAL_DOMAIN_KEIL
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_DOMAIN_ARMCompiler        NCAOL_SPECS_COMP_VAL_DOMAIN_ARMCompiler
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_DOMAIN_Clang              NCAOL_SPECS_COMP_VAL_DOMAIN_Clang
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_DOMAIN_GCC                NCAOL_SPECS_COMP_VAL_DOMAIN_GCC
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_DOMAIN_MicrosoftVisualCPP NCAOL_SPECS_COMP_VAL_DOMAIN_MicrosoftVisualCPP
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_DOMAIN_MinGW              NCAOL_SPECS_COMP_VAL_DOMAIN_MinGW

#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_NAME_MicroBlazeC        NCAOL_SPECS_COMP_VAL_NAME_MicroBlazeC
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_NAME_CtoHardware        NCAOL_SPECS_COMP_VAL_NAME_CtoHardware
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_NAME_CARM               NCAOL_SPECS_COMP_VAL_NAME_CARM
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_NAME_C166               NCAOL_SPECS_COMP_VAL_NAME_C166
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_NAME_C51                NCAOL_SPECS_COMP_VAL_NAME_C51
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_NAME_ARMCompiler        NCAOL_SPECS_COMP_VAL_NAME_ARMCompiler
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_NAME_Clang              NCAOL_SPECS_COMP_VAL_NAME_Clang
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_NAME_GCC                NCAOL_SPECS_COMP_VAL_NAME_GCC
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_NAME_MicrosoftVisualCPP NCAOL_SPECS_COMP_VAL_NAME_MicrosoftVisualCPP
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_NAME_MinGW32            NCAOL_SPECS_COMP_VAL_NAME_MinGW32
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_NAME_MinGWw64_32B       NCAOL_SPECS_COMP_VAL_NAME_MinGWw64_32B
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_NAME_MinGWw64_64B       NCAOL_SPECS_COMP_VAL_NAME_MinGWw64_64B

#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_ID_MicroBlazeC        NCAOL_SPECS_COMP_VAL_ID_MicroBlazeC
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_ID_CtoHardware        NCAOL_SPECS_COMP_VAL_ID_CtoHardware
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_ID_CARM               NCAOL_SPECS_COMP_VAL_ID_CARM
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_ID_C166               NCAOL_SPECS_COMP_VAL_ID_C166
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_ID_C51                NCAOL_SPECS_COMP_VAL_ID_C51
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_ID_ARMCompiler        NCAOL_SPECS_COMP_VAL_ID_ARMCompiler
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_ID_Clang              NCAOL_SPECS_COMP_VAL_ID_Clang
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_ID_GCC                NCAOL_SPECS_COMP_VAL_ID_GCC
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_ID_MicrosoftVisualCPP NCAOL_SPECS_COMP_VAL_ID_MicrosoftVisualCPP
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_ID_MinGW32            NCAOL_SPECS_COMP_VAL_ID_MinGW32
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_ID_MinGWw64_32B       NCAOL_SPECS_COMP_VAL_ID_MinGWw64_32B
#define NCAOL_SPECS_COMP_INTER_NCAOL_COMPILER_ID_MinGWw64_64B       NCAOL_SPECS_COMP_VAL_ID_MinGWw64_64B


#define NCAOL_SPECS_COMP_INTER_NCAOL_CURRENT_COMPILER_SUBJECT NCAOL_SPECS_COMP_DEF_COMPILER_SUBJECT
#define NCAOL_SPECS_COMP_INTER_NCAOL_CURRENT_COMPILER_DOMAIN  NCAOL_SPECS_COMP_DEF_COMPILER_DOMAIN
#define NCAOL_SPECS_COMP_INTER_NCAOL_CURRENT_COMPILER_NAME    NCAOL_SPECS_COMP_DEF_COMPILER_NAME
#define NCAOL_SPECS_COMP_INTER_NCAOL_CURRENT_COMPILER_ID      NCAOL_SPECS_COMP_DEF_COMPILER_ID

#define NCAOL_SPECS_COMP_INTER_NCAOL_CURRENT_FUNC NCAOL_SPECS_COMP_DEF_CURRENT_FUNC
#define NCAOL_SPECS_COMP_INTER_NCAOL_CURRENT_FILE NCAOL_SPECS_COMP_DEF_CURRENT_FILE
#define NCAOL_SPECS_COMP_INTER_NCAOL_CURRENT_LINE NCAOL_SPECS_COMP_DEF_CURRENT_LINE
#define NCAOL_SPECS_COMP_INTER_NCAOL_CURRENT_DATE NCAOL_SPECS_COMP_DEF_CURRENT_DATE
#define NCAOL_SPECS_COMP_INTER_NCAOL_CURRENT_TIME NCAOL_SPECS_COMP_DEF_CURRENT_TIME


#define NCAOL_SPECS_COMP_INTER_NCAOL_EXT_NAMESPACE      NCAOL_SPECS_COMP_DEF_EXTENSION_NAMESPACE
#define NCAOL_SPECS_COMP_INTER_NCAOL_EXT_START          NCAOL_SPECS_COMP_DEF_EXTENSION_WRAP_START
#define NCAOL_SPECS_COMP_INTER_NCAOL_EXT_STOP           NCAOL_SPECS_COMP_DEF_EXTENSION_WRAP_STOP
#define NCAOL_SPECS_COMP_INTER_NCAOL_EXT_GET(NCAOLext)  NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_##NCAOLext
#define NCAOL_SPECS_COMP_INTER_NCAOL_EXT_WRAP(NCAOLext) NCAOL_SPECS_COMP_DEF_EXTENSION_WRAP_FUNC(NCAOL_SPECS_COMP_INTER_NCAOL_EXT_GET(NCAOLext))


#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLalias(NCAOLtarget)                            NCAOL_SPECS_COMP_DEF_EXTNAME_alias(NCAOLtarget)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLaligned(NCAOLalignment)                       NCAOL_SPECS_COMP_DEF_EXTNAME_aligned(NCAOLalignment)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLalloc_align(NCAOLposition)                    NCAOL_SPECS_COMP_DEF_EXTNAME_alloc_align(NCAOLposition)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLalloc_size(NCAOL_VA_ARGS)                     NCAOL_SPECS_COMP_DEF_EXTNAME_alloc_size(NCAOL_VA_ARGS)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLalways_inline                                 NCAOL_SPECS_COMP_DEF_EXTNAME_always_inline static inline
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLartificial                                    NCAOL_SPECS_COMP_DEF_EXTNAME_artificial
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLassume_aligned(NCAOL_VA_ARGS)                 NCAOL_SPECS_COMP_DEF_EXTNAME_assume_aligned(NCAOL_VA_ARGS)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLbtf_decl_tag(NCAOLstr)                        NCAOL_SPECS_COMP_DEF_EXTNAME_btf_decl_tag(NCAOLstr)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLbtf_type_tag(NCAOLarg)                        NCAOL_SPECS_COMP_DEF_EXTNAME_btf_type_tag(NCAOLarg)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLcleanup(NCAOLfunc)                            NCAOL_SPECS_COMP_DEF_EXTNAME_cleanup(NCAOLfunc)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLcold                                          NCAOL_SPECS_COMP_DEF_EXTNAME_cold
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLhot                                           NCAOL_SPECS_COMP_DEF_EXTNAME_hot
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLcommon                                        NCAOL_SPECS_COMP_DEF_EXTNAME_common
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLnocommon                                      NCAOL_SPECS_COMP_DEF_EXTNAME_nocommon
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLconst                                         NCAOL_SPECS_COMP_DEF_EXTNAME_const
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLconstructor(NCAOLpriority)                    NCAOL_SPECS_COMP_DEF_EXTNAME_constructor(NCAOLpriority)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLdestructor(NCAOLpriority)                     NCAOL_SPECS_COMP_DEF_EXTNAME_destructor(NCAOLpriority)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLcounted_by(NCAOLcount)                        NCAOL_SPECS_COMP_DEF_EXTNAME_counted_by(NCAOLcount)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLdeprecated(NCAOLmsg)                          NCAOL_SPECS_COMP_DEF_EXTNAME_deprecated(NCAOLmsg)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLerror(NCAOLmsg)                               NCAOL_SPECS_COMP_DEF_EXTNAME_error(NCAOLmsg)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLwarning(NCAOLmsg)                             NCAOL_SPECS_COMP_DEF_EXTNAME_warning(NCAOLmsg)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLflag_enum                                     NCAOL_SPECS_COMP_DEF_EXTNAME_flag_enum
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLflatten                                       NCAOL_SPECS_COMP_DEF_EXTNAME_flatten
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLformat(NCAOLarchT, NCAOLindex, NCAOLcheck)    NCAOL_SPECS_COMP_DEF_EXTNAME_format(NCAOLarchT, NCAOLindex, NCAOLcheck)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLformat_arg(NCAOLstring_index)                 NCAOL_SPECS_COMP_DEF_EXTNAME_format_arg(NCAOLstring_index)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLgnu_inline                                    NCAOL_SPECS_COMP_DEF_EXTNAME_gnu_inline
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLifunc(NCAOLresolver)                          NCAOL_SPECS_COMP_DEF_EXTNAME_ifunc(NCAOLresolver)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLinterrupt                                     NCAOL_SPECS_COMP_DEF_EXTNAME_interrupt
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLleaf                                          NCAOL_SPECS_COMP_DEF_EXTNAME_leaf
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLmalloc(NCAOL_VA_ARGS)                         NCAOL_SPECS_COMP_DEF_EXTNAME_malloc(NCAOL_VA_ARGS)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLmay_alias                                     NCAOL_SPECS_COMP_DEF_EXTNAME_may_alias
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLmode(NCAOLmode)                               NCAOL_SPECS_COMP_DEF_EXTNAME_mode(NCAOLmode)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLmusttail                                      NCAOL_SPECS_COMP_DEF_EXTNAME_musttail
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLnaked                                         NCAOL_SPECS_COMP_DEF_EXTNAME_naked
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLno_profile_instrument_function                NCAOL_SPECS_COMP_DEF_EXTNAME_no_profile_instrument_function
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLno_sanitize(NCAOLoption)                      NCAOL_SPECS_COMP_DEF_EXTNAME_no_sanitize(NCAOLoption)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLno_sanitize_address                           NCAOL_SPECS_COMP_DEF_EXTNAME_no_sanitize_address
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLno_sanitize_thread                            NCAOL_SPECS_COMP_DEF_EXTNAME_no_sanitize_thread
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLno_split_stack                                NCAOL_SPECS_COMP_DEF_EXTNAME_no_split_stack
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLno_stack_protector                            NCAOL_SPECS_COMP_DEF_EXTNAME_no_stack_protector
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLnoinline                                      NCAOL_SPECS_COMP_DEF_EXTNAME_noinline
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLnonnull(NCAOL_VA_ARGS)                        NCAOL_SPECS_COMP_DEF_EXTNAME_nonnull(NCAOL_VA_ARGS)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLnonstring                                     NCAOL_SPECS_COMP_DEF_EXTNAME_nonstring
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLnoreturn                                      NCAOL_SPECS_COMP_DEF_EXTNAME_noreturn
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLnothrow                                       NCAOL_SPECS_COMP_DEF_EXTNAME_nothrow
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLoptimize                                      NCAOL_SPECS_COMP_DEF_EXTNAME_optimize
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLpacked                                        NCAOL_SPECS_COMP_DEF_EXTNAME_packed
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLpatchable_function_entry                      NCAOL_SPECS_COMP_DEF_EXTNAME_patchable_function_entry
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLpure                                          NCAOL_SPECS_COMP_DEF_EXTNAME_pure
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLreproducible                                  NCAOL_SPECS_COMP_DEF_EXTNAME_reproducible
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLretain                                        NCAOL_SPECS_COMP_DEF_EXTNAME_retain
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLreturns_nonnull                               NCAOL_SPECS_COMP_DEF_EXTNAME_returns_nonnull
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLreturns_twice                                 NCAOL_SPECS_COMP_DEF_EXTNAME_returns_twice
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLsection(NCAOLsection)                         NCAOL_SPECS_COMP_DEF_EXTNAME_section(NCAOLsection)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLsentinel(NCAOLposition)                       NCAOL_SPECS_COMP_DEF_EXTNAME_sentinel(NCAOLposition)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLtarget(NCAOL_VA_ARGS)                         NCAOL_SPECS_COMP_DEF_EXTNAME_target(NCAOL_VA_ARGS)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLtarget_version(NCAOLoption)                   NCAOL_SPECS_COMP_DEF_EXTNAME_target_version(NCAOLoption)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLtarget_clones(NCAOLoptions)                   NCAOL_SPECS_COMP_DEF_EXTNAME_target_clones(NCAOLoptions)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLtls_model(NCAOLtls_model)                     NCAOL_SPECS_COMP_DEF_EXTNAME_tls_model(NCAOLtls_model)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLtransparent_union                             NCAOL_SPECS_COMP_DEF_EXTNAME_transparent_union
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLunavailable(NCAOLmsg)                         NCAOL_SPECS_COMP_DEF_EXTNAME_unavailable(NCAOLmsg)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLuninitialized                                 NCAOL_SPECS_COMP_DEF_EXTNAME_uninitialized
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLunsequenced                                   NCAOL_SPECS_COMP_DEF_EXTNAME_unsequenced
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLmaybe_unused                                  NCAOL_SPECS_COMP_DEF_EXTNAME_maybe_unused
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLused                                          NCAOL_SPECS_COMP_DEF_EXTNAME_used
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLvector_size(NCAOLbytes)                       NCAOL_SPECS_COMP_DEF_EXTNAME_vector_size(NCAOLbytes)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLvisibility(NCAOLvisibility_type)              NCAOL_SPECS_COMP_DEF_EXTNAME_visibility(NCAOLvisibility_type)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLnodiscard                                     NCAOL_SPECS_COMP_DEF_EXTNAME_nodiscard
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLweak                                          NCAOL_SPECS_COMP_DEF_EXTNAME_weak
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLweakref(NCAOLtarget)                          NCAOL_SPECS_COMP_DEF_EXTNAME_weakref(NCAOLtarget)
#define NCAOL_SPECS_COMP_INTER_EXTENSION_NAME_NCAOLzero_call_used_regs(NCAOLchoice)              NCAOL_SPECS_COMP_DEF_EXTNAME_zero_call_used_regs(NCAOLchoice)



//cstdlibrary.h
#define caolSpecsCSTDLIB(NCAOLarg) NCAOL_SPECS_CSTDLIB_INTER_##NCAOLarg
#define NCAOL_SPECS_CSTDLIB_INTER_NCAOL_LIB_NAME_Bionic  NCAOL_SPECS_CSTDLIB_VAL_NAME_Bionic
#define NCAOL_SPECS_CSTDLIB_INTER_NCAOL_LIB_NAME_glibc   NCAOL_SPECS_CSTDLIB_VAL_NAME_glibc
#define NCAOL_SPECS_CSTDLIB_INTER_NCAOL_LIB_NAME_klibc   NCAOL_SPECS_CSTDLIB_VAL_NAME_klibc
#define NCAOL_SPECS_CSTDLIB_INTER_NCAOL_LIB_NAME_uClibc  NCAOL_SPECS_CSTDLIB_VAL_NAME_uClibc
#define NCAOL_SPECS_CSTDLIB_INTER_NCAOL_LIB_NAME_zOSlib  NCAOL_SPECS_CSTDLIB_VAL_NAME_zOSlib
#define NCAOL_SPECS_CSTDLIB_INTER_NCAOL_LIB_NAME_WINDOWS NCAOL_SPECS_CSTDLIB_VAL_NAME_WINDOWS

#define NCAOL_SPECS_CSTDLIB_INTER_NCAOL_LIB_ID_Bionic  NCAOL_SPECS_CSTDLIB_VAL_ID_Bionic
#define NCAOL_SPECS_CSTDLIB_INTER_NCAOL_LIB_ID_glibc   NCAOL_SPECS_CSTDLIB_VAL_ID_glibc
#define NCAOL_SPECS_CSTDLIB_INTER_NCAOL_LIB_ID_klibc   NCAOL_SPECS_CSTDLIB_VAL_ID_klibc
#define NCAOL_SPECS_CSTDLIB_INTER_NCAOL_LIB_ID_uClibc  NCAOL_SPECS_CSTDLIB_VAL_ID_uClibc
#define NCAOL_SPECS_CSTDLIB_INTER_NCAOL_LIB_ID_zOSlib  NCAOL_SPECS_CSTDLIB_VAL_ID_zOSlib
#define NCAOL_SPECS_CSTDLIB_INTER_NCAOL_LIB_ID_WINDOWS NCAOL_SPECS_CSTDLIB_VAL_ID_WINDOWS


#define NCAOL_SPECS_CSTDLIB_INTER_NCAOL_CURRENT_LIB_NAME NCAOL_SPECS_CSTDLIB_DEF_LIB_NAME
#define NCAOL_SPECS_CSTDLIB_INTER_NCAOL_CURRENT_LIB_ID   NCAOL_SPECS_CSTDLIB_DEF_LIB_ID



//OS.h
#define caolSpecsOS(NCAOLarg) NCAOL_SPECS_OS_INTER_##NCAOLarg
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_SUBJECT_PDP7     NCAOL_SPECS_OS_VAL_SUBJECT_PDP7
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_SUBJECT_UnixLike NCAOL_SPECS_OS_VAL_SUBJECT_UnixLike
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_SUBJECT_Unix     NCAOL_SPECS_OS_VAL_SUBJECT_Unix
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_SUBJECT_DOS      NCAOL_SPECS_OS_VAL_SUBJECT_DOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_SUBJECT_Other    NCAOL_SPECS_OS_VAL_SUBJECT_Other

#define NCAOL_SPECS_OS_INTER_NCAOL_OS_DOMAIN_PWBUnix    NCAOL_SPECS_OS_VAL_DOMAIN_PWBUnix
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_DOMAIN_BSD        NCAOL_SPECS_OS_VAL_DOMAIN_BSD
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_DOMAIN_Unix32V    NCAOL_SPECS_OS_VAL_DOMAIN_Unix32V
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_DOMAIN_SystemIII  NCAOL_SPECS_OS_VAL_DOMAIN_SystemIII
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_DOMAIN_SystemV    NCAOL_SPECS_OS_VAL_DOMAIN_SystemV
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_DOMAIN_SystemV_R1 NCAOL_SPECS_OS_VAL_DOMAIN_SystemV_R1
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_DOMAIN_SystemV_R2 NCAOL_SPECS_OS_VAL_DOMAIN_SystemV_R2
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_DOMAIN_SystemV_R3 NCAOL_SPECS_OS_VAL_DOMAIN_SystemV_R3
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_DOMAIN_SystemV_R4 NCAOL_SPECS_OS_VAL_DOMAIN_SystemV_R4
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_DOMAIN_SystemV_R5 NCAOL_SPECS_OS_VAL_DOMAIN_SystemV_R5
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_DOMAIN_OSF1       NCAOL_SPECS_OS_VAL_DOMAIN_OSF1
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_DOMAIN_MSDOS      NCAOL_SPECS_OS_VAL_DOMAIN_MSDOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_DOMAIN_OS2        NCAOL_SPECS_OS_VAL_DOMAIN_OS2
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_DOMAIN_Windows    NCAOL_SPECS_OS_VAL_DOMAIN_Windows
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_DOMAIN_Other      NCAOL_SPECS_OS_VAL_DOMAIN_Other

#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_AIX                 NCAOL_SPECS_OS_VAL_ID_AIX
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_Android             NCAOL_SPECS_OS_VAL_ID_Android
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_Amdahl_UTS          NCAOL_SPECS_OS_VAL_ID_Amdahl_UTS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_AmigaOS             NCAOL_SPECS_OS_VAL_ID_AmigaOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_Apollo_AEGIS        NCAOL_SPECS_OS_VAL_ID_Apollo_AEGIS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_Apollo_DomainOS     NCAOL_SPECS_OS_VAL_ID_Apollo_DomainOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_BeOS                NCAOL_SPECS_OS_VAL_ID_BeOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_BlueGene            NCAOL_SPECS_OS_VAL_ID_BlueGene
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_BSD_Environment     NCAOL_SPECS_OS_VAL_ID_BSD_Environment
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_BSD_OS              NCAOL_SPECS_OS_VAL_ID_BSD_OS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_ConvexOS            NCAOL_SPECS_OS_VAL_ID_ConvexOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_Cygwin_Environment  NCAOL_SPECS_OS_VAL_ID_Cygwin_Environment
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_DG_UX               NCAOL_SPECS_OS_VAL_ID_DG_UX
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_DragonFly           NCAOL_SPECS_OS_VAL_ID_DragonFly
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_DYNIX_ptx           NCAOL_SPECS_OS_VAL_ID_DYNIX_ptx
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_eCos                NCAOL_SPECS_OS_VAL_ID_eCos
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_EMX_Environment     NCAOL_SPECS_OS_VAL_ID_EMX_Environment
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_FreeBSD             NCAOL_SPECS_OS_VAL_ID_FreeBSD
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_GNU_Hurd            NCAOL_SPECS_OS_VAL_ID_GNU_Hurd
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_GNU_kFreeBSD        NCAOL_SPECS_OS_VAL_ID_GNU_kFreeBSD
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_GNU_Linux           NCAOL_SPECS_OS_VAL_ID_GNU_Linux
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_HIUX_MPP            NCAOL_SPECS_OS_VAL_ID_HIUX_MPP
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_HPUX                NCAOL_SPECS_OS_VAL_ID_HPUX
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_IBM_OS400           NCAOL_SPECS_OS_VAL_ID_IBM_OS400
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_INTEGRITY           NCAOL_SPECS_OS_VAL_ID_INTEGRITY
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_Interix_Environment NCAOL_SPECS_OS_VAL_ID_Interix_Environment
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_IRIX                NCAOL_SPECS_OS_VAL_ID_IRIX
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_Linux_kernel        NCAOL_SPECS_OS_VAL_ID_Linux_kernel
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_LynxOS              NCAOL_SPECS_OS_VAL_ID_LynxOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_MacOS_9             NCAOL_SPECS_OS_VAL_ID_MacOS_9
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_MacOS_X             NCAOL_SPECS_OS_VAL_ID_MacOS_X
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_Microware_OS9       NCAOL_SPECS_OS_VAL_ID_Microware_OS9
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_MINIX               NCAOL_SPECS_OS_VAL_ID_MINIX
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_MorphOS             NCAOL_SPECS_OS_VAL_ID_MorphOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_MPE_iX              NCAOL_SPECS_OS_VAL_ID_MPE_iX
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_MSDOS               NCAOL_SPECS_OS_VAL_ID_MSDOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_NetBSD              NCAOL_SPECS_OS_VAL_ID_NetBSD
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_NonStop             NCAOL_SPECS_OS_VAL_ID_NonStop
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_NucleusRTOS         NCAOL_SPECS_OS_VAL_ID_NucleusRTOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_OpenBSD             NCAOL_SPECS_OS_VAL_ID_OpenBSD
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_OS2                 NCAOL_SPECS_OS_VAL_ID_OS2
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_PalmOS              NCAOL_SPECS_OS_VAL_ID_PalmOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_Plan9               NCAOL_SPECS_OS_VAL_ID_Plan9
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_Pyramid_DCOSx       NCAOL_SPECS_OS_VAL_ID_Pyramid_DCOSx
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_QNX                 NCAOL_SPECS_OS_VAL_ID_QNX
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_Reliant_UNIX        NCAOL_SPECS_OS_VAL_ID_Reliant_UNIX
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_SCO_OpenServer      NCAOL_SPECS_OS_VAL_ID_SCO_OpenServer
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_Solaris             NCAOL_SPECS_OS_VAL_ID_Solaris
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_Stratus_VOS         NCAOL_SPECS_OS_VAL_ID_Stratus_VOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_SVR4_Environment    NCAOL_SPECS_OS_VAL_ID_SVR4_Environment
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_Syllable            NCAOL_SPECS_OS_VAL_ID_Syllable
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_SymbianOS           NCAOL_SPECS_OS_VAL_ID_SymbianOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_Tru64_OSF1          NCAOL_SPECS_OS_VAL_ID_Tru64_OSF1
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_Ultrix              NCAOL_SPECS_OS_VAL_ID_Ultrix
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_UNICOS              NCAOL_SPECS_OS_VAL_ID_UNICOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_UNICOS_mp           NCAOL_SPECS_OS_VAL_ID_UNICOS_mp
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_UNIX_Environment    NCAOL_SPECS_OS_VAL_ID_UNIX_Environment
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_UnixWare            NCAOL_SPECS_OS_VAL_ID_UnixWare
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_UWin_Environment    NCAOL_SPECS_OS_VAL_ID_UWin_Environment
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_OpenVMS             NCAOL_SPECS_OS_VAL_ID_OpenVMS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_VxWorks             NCAOL_SPECS_OS_VAL_ID_VxWorks
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_Windows             NCAOL_SPECS_OS_VAL_ID_Windows
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_Windows_CE          NCAOL_SPECS_OS_VAL_ID_Windows_CE
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_WindU_Environment   NCAOL_SPECS_OS_VAL_ID_WindU_Environment
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_ID_zOS                 NCAOL_SPECS_OS_VAL_ID_zOS

#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_AIX                 NCAOL_SPECS_OS_VAL_NAME_AIX
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_Android             NCAOL_SPECS_OS_VAL_NAME_Android
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_Amdahl_UTS          NCAOL_SPECS_OS_VAL_NAME_Amdahl_UTS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_AmigaOS             NCAOL_SPECS_OS_VAL_NAME_AmigaOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_Apollo_AEGIS        NCAOL_SPECS_OS_VAL_NAME_Apollo_AEGIS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_Apollo_DomainOS     NCAOL_SPECS_OS_VAL_NAME_Apollo_DomainOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_BeOS                NCAOL_SPECS_OS_VAL_NAME_BeOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_BlueGene            NCAOL_SPECS_OS_VAL_NAME_BlueGene
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_BSD_Environment     NCAOL_SPECS_OS_VAL_NAME_BSD_Environment
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_BSD_OS              NCAOL_SPECS_OS_VAL_NAME_BSD_OS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_ConvexOS            NCAOL_SPECS_OS_VAL_NAME_ConvexOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_Cygwin_Environment  NCAOL_SPECS_OS_VAL_NAME_Cygwin_Environment
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_DG_UX               NCAOL_SPECS_OS_VAL_NAME_DG_UX
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_DragonFly           NCAOL_SPECS_OS_VAL_NAME_DragonFly
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_DYNIX_ptx           NCAOL_SPECS_OS_VAL_NAME_DYNIX_ptx
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_eCos                NCAOL_SPECS_OS_VAL_NAME_eCos
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_EMX_Environment     NCAOL_SPECS_OS_VAL_NAME_EMX_Environment
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_FreeBSD             NCAOL_SPECS_OS_VAL_NAME_FreeBSD
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_GNU_Hurd            NCAOL_SPECS_OS_VAL_NAME_GNU_Hurd
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_GNU_kFreeBSD        NCAOL_SPECS_OS_VAL_NAME_GNU_kFreeBSD
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_GNU_Linux           NCAOL_SPECS_OS_VAL_NAME_GNU_Linux
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_HIUX_MPP            NCAOL_SPECS_OS_VAL_NAME_HIUX_MPP
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_HPUX                NCAOL_SPECS_OS_VAL_NAME_HPUX
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_IBM_OS400           NCAOL_SPECS_OS_VAL_NAME_IBM_OS400
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_INTEGRITY           NCAOL_SPECS_OS_VAL_NAME_INTEGRITY
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_Interix_Environment NCAOL_SPECS_OS_VAL_NAME_Interix_Environment
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_IRIX                NCAOL_SPECS_OS_VAL_NAME_IRIX
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_Linux_kernel        NCAOL_SPECS_OS_VAL_NAME_Linux_kernel
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_LynxOS              NCAOL_SPECS_OS_VAL_NAME_LynxOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_MacOS_9             NCAOL_SPECS_OS_VAL_NAME_MacOS_9
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_MacOS_X             NCAOL_SPECS_OS_VAL_NAME_MacOS_X
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_Microware_OS9       NCAOL_SPECS_OS_VAL_NAME_Microware_OS9
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_MINIX               NCAOL_SPECS_OS_VAL_NAME_MINIX
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_MorphOS             NCAOL_SPECS_OS_VAL_NAME_MorphOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_MPE_iX              NCAOL_SPECS_OS_VAL_NAME_MPE_iX
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_MSDOS               NCAOL_SPECS_OS_VAL_NAME_MSDOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_NetBSD              NCAOL_SPECS_OS_VAL_NAME_NetBSD
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_NonStop             NCAOL_SPECS_OS_VAL_NAME_NonStop
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_NucleusRTOS         NCAOL_SPECS_OS_VAL_NAME_NucleusRTOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_OpenBSD             NCAOL_SPECS_OS_VAL_NAME_OpenBSD
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_OS2                 NCAOL_SPECS_OS_VAL_NAME_OS2
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_PalmOS              NCAOL_SPECS_OS_VAL_NAME_PalmOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_Plan9               NCAOL_SPECS_OS_VAL_NAME_Plan9
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_Pyramid_DCOSx       NCAOL_SPECS_OS_VAL_NAME_Pyramid_DCOSx
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_QNX                 NCAOL_SPECS_OS_VAL_NAME_QNX
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_Reliant_UNIX        NCAOL_SPECS_OS_VAL_NAME_Reliant_UNIX
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_SCO_OpenServer      NCAOL_SPECS_OS_VAL_NAME_SCO_OpenServer
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_Solaris             NCAOL_SPECS_OS_VAL_NAME_Solaris
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_Stratus_VOS         NCAOL_SPECS_OS_VAL_NAME_Stratus_VOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_SVR4_Environment    NCAOL_SPECS_OS_VAL_NAME_SVR4_Environment
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_Syllable            NCAOL_SPECS_OS_VAL_NAME_Syllable
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_SymbianOS           NCAOL_SPECS_OS_VAL_NAME_SymbianOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_Tru64_OSF1          NCAOL_SPECS_OS_VAL_NAME_Tru64_OSF1
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_Ultrix              NCAOL_SPECS_OS_VAL_NAME_Ultrix
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_UNICOS              NCAOL_SPECS_OS_VAL_NAME_UNICOS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_UNICOS_mp           NCAOL_SPECS_OS_VAL_NAME_UNICOS_mp
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_UNIX_Environment    NCAOL_SPECS_OS_VAL_NAME_UNIX_Environment
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_UnixWare            NCAOL_SPECS_OS_VAL_NAME_UnixWare
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_UWin_Environment    NCAOL_SPECS_OS_VAL_NAME_UWin_Environment
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_OpenVMS             NCAOL_SPECS_OS_VAL_NAME_OpenVMS
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_VxWorks             NCAOL_SPECS_OS_VAL_NAME_VxWorks
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_Windows             NCAOL_SPECS_OS_VAL_NAME_Windows
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_Windows_CE          NCAOL_SPECS_OS_VAL_NAME_Windows_CE
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_WindU_Environment   NCAOL_SPECS_OS_VAL_NAME_WindU_Environment
#define NCAOL_SPECS_OS_INTER_NCAOL_OS_NAME_zOS                 NCAOL_SPECS_OS_VAL_NAME_zOS


#define NCAOL_SPECS_OS_INTER_NCAOL_CURRENT_OS_SUBJECT NCAOL_SPECS_OS_DEF_OS_SUBJECT
#define NCAOL_SPECS_OS_INTER_NCAOL_CURRENT_OS_DOMAIN  NCAOL_SPECS_OS_DEF_OS_DOMAIN
#define NCAOL_SPECS_OS_INTER_NCAOL_CURRENT_OS_NAME    NCAOL_SPECS_OS_DEF_OS_NAME
#define NCAOL_SPECS_OS_INTER_NCAOL_CURRENT_OS_ID      NCAOL_SPECS_OS_DEF_OS_ID



//architecture.h
#define caolSpecsArch(NCAOLarg) NCAOL_SPECS_ARCH_INTER_##NCAOLarg
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_CLASS_RISC NCAOL_SPECS_ARCH_VAL_CLASS_RISC
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_CLASS_EPIC NCAOL_SPECS_ARCH_VAL_CLASS_EPIC
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_CLASS_CISC NCAOL_SPECS_ARCH_VAL_CLASS_CISC

#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_NAME_Alpha             NCAOL_SPECS_ARCH_VAL_NAME_Alpha
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_NAME_ARM               NCAOL_SPECS_ARCH_VAL_NAME_ARM
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_NAME_ARM_Thumb         NCAOL_SPECS_ARCH_VAL_NAME_ARM_Thumb
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_NAME_ARM64             NCAOL_SPECS_ARCH_VAL_NAME_ARM64
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_NAME_Blackfin          NCAOL_SPECS_ARCH_VAL_NAME_Blackfin
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_NAME_MIPS              NCAOL_SPECS_ARCH_VAL_NAME_MIPS
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_NAME_PowerPC           NCAOL_SPECS_ARCH_VAL_NAME_PowerPC
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_NAME_PowerPC64         NCAOL_SPECS_ARCH_VAL_NAME_PowerPC64
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_NAME_RS6000            NCAOL_SPECS_ARCH_VAL_NAME_RS6000
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_NAME_SPARC             NCAOL_SPECS_ARCH_VAL_NAME_SPARC
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_NAME_SuperH            NCAOL_SPECS_ARCH_VAL_NAME_SuperH
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_NAME_IntelItanium_IA64 NCAOL_SPECS_ARCH_VAL_NAME_IntelItanium_IA64
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_NAME_x86_64            NCAOL_SPECS_ARCH_VAL_NAME_x86_64
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_NAME_Intel_x86         NCAOL_SPECS_ARCH_VAL_NAME_Intel_x86
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_NAME_Intel_x86_16Bit   NCAOL_SPECS_ARCH_VAL_NAME_Intel_x86_16Bit
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_NAME_Motorola68k       NCAOL_SPECS_ARCH_VAL_NAME_Motorola68k
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_NAME_SystemZ           NCAOL_SPECS_ARCH_VAL_NAME_SystemZ

#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_ID_Alpha             NCAOL_SPECS_ARCH_VAL_ID_Alpha
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_ID_ARM               NCAOL_SPECS_ARCH_VAL_ID_ARM
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_ID_ARM_Thumb         NCAOL_SPECS_ARCH_VAL_ID_ARM_Thumb
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_ID_ARM64             NCAOL_SPECS_ARCH_VAL_ID_ARM64
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_ID_Blackfin          NCAOL_SPECS_ARCH_VAL_ID_Blackfin
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_ID_MIPS              NCAOL_SPECS_ARCH_VAL_ID_MIPS
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_ID_PowerPC           NCAOL_SPECS_ARCH_VAL_ID_PowerPC
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_ID_PowerPC64         NCAOL_SPECS_ARCH_VAL_ID_PowerPC64
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_ID_RS6000            NCAOL_SPECS_ARCH_VAL_ID_RS6000
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_ID_SPARC             NCAOL_SPECS_ARCH_VAL_ID_SPARC
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_ID_SuperH            NCAOL_SPECS_ARCH_VAL_ID_SuperH
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_ID_IntelItanium_IA64 NCAOL_SPECS_ARCH_VAL_ID_IntelItanium_IA64
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_ID_x86_64            NCAOL_SPECS_ARCH_VAL_ID_x86_64
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_ID_Intel_x86         NCAOL_SPECS_ARCH_VAL_ID_Intel_x86
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_ID_Intel_x86_16Bit   NCAOL_SPECS_ARCH_VAL_ID_Intel_x86_16Bit
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_ID_Motorola68k       NCAOL_SPECS_ARCH_VAL_ID_Motorola68k
#define NCAOL_SPECS_ARCH_INTER_NCAOL_ARCH_ID_SystemZ           NCAOL_SPECS_ARCH_VAL_ID_SystemZ


#define NCAOL_SPECS_ARCH_INTER_NCAOL_CURRENT_ARCH_CLASS NCAOL_SPECS_ARCH_DEF_ARCH_CLASS
#define NCAOL_SPECS_ARCH_INTER_NCAOL_CURRENT_ARCH_NAME  NCAOL_SPECS_ARCH_DEF_ARCH_NAME
#define NCAOL_SPECS_ARCH_INTER_NCAOL_CURRENT_ARCH_ID    NCAOL_SPECS_ARCH_DEF_ARCH_ID


#endif