#ifndef NIGMA_CAOL_SPECIFICS_OS_H
#define NIGMA_CAOL_SPECIFICS_OS_H


#include "cstdlibrary.h"
#include "ID/OS.h"

//CSTDLIB specific identifications:
#if (NCAOL_SPECS_CSTDLIB_DEF_LIB_ID == NCAOL_SPECS_CSTDLIB_VAL_ID_Bionic)
#elif (NCAOL_SPECS_CSTDLIB_DEF_LIB_ID == NCAOL_SPECS_CSTDLIB_VAL_ID_glibc)
    #if (defined(M_I386) || defined(M_XENIX))
        #if (defined(__unix__) || defined(__unix))
            #define NCAOL_SPECS_OS_DEF_OS_SUBJECT NCAOL_SPECS_OS_VAL_SUBJECT_Unix
        #else
            #define NCAOL_SPECS_OS_DEF_OS_SUBJECT NCAOL_SPECS_OS_VAL_SUBJECT_UnixLike
        #endif
        #define NCAOL_SPECS_OS_DEF_OS_DOMAIN NCAOL_SPECS_OS_VAL_DOMAIN_SystemV_R5
        #define NCAOL_SPECS_OS_DEF_OS_NAME   NCAOL_SPECS_OS_VAL_NAME_SCO_OpenServer
        #define NCAOL_SPECS_OS_DEF_OS_ID     NCAOL_SPECS_OS_VAL_ID_SCO_OpenServer
    #elif defined(__INTERIX)
        #define NCAOL_SPECS_OS_DEF_OS_SUBJECT NCAOL_SPECS_OS_VAL_SUBJECT_DOS
        #define NCAOL_SPECS_OS_DEF_OS_DOMAIN  NCAOL_SPECS_OS_VAL_DOMAIN_Windows
        #define NCAOL_SPECS_OS_DEF_OS_NAME    NCAOL_SPECS_OS_VAL_NAME_Interix_Environment
        #define NCAOL_SPECS_OS_DEF_OS_ID      NCAOL_SPECS_OS_VAL_ID_Interix_Environment
    #elif defined(__amigaos__)
        #define NCAOL_SPECS_OS_DEF_OS_SUBJECT NCAOL_SPECS_OS_VAL_SUBJECT_Other
        #define NCAOL_SPECS_OS_DEF_OS_DOMAIN  NCAOL_SPECS_OS_VAL_DOMAIN_Other
        #define NCAOL_SPECS_OS_DEF_OS_NAME    NCAOL_SPECS_OS_VAL_NAME_AmigaOS
        #define NCAOL_SPECS_OS_DEF_OS_ID      NCAOL_SPECS_OS_VAL_ID_AmigaOS
    #elif defined(__bg__)
        #define NCAOL_SPECS_OS_DEF_OS_SUBJECT NCAOL_SPECS_OS_VAL_SUBJECT_Other
        #define NCAOL_SPECS_OS_DEF_OS_DOMAIN  NCAOL_SPECS_OS_VAL_DOMAIN_Other
        #define NCAOL_SPECS_OS_DEF_OS_NAME    NCAOL_SPECS_OS_VAL_NAME_BlueGene
        #define NCAOL_SPECS_OS_DEF_OS_ID      NCAOL_SPECS_OS_VAL_ID_BlueGene
    #elif defined(__palmos__)
        #define NCAOL_SPECS_OS_DEF_OS_SUBJECT NCAOL_SPECS_OS_VAL_SUBJECT_Other
        #define NCAOL_SPECS_OS_DEF_OS_DOMAIN  NCAOL_SPECS_OS_VAL_DOMAIN_Other
        #define NCAOL_SPECS_OS_DEF_OS_NAME    NCAOL_SPECS_OS_VAL_NAME_PalmOS
        #define NCAOL_SPECS_OS_DEF_OS_ID      NCAOL_SPECS_OS_VAL_ID_PalmOS
    #elif (defined(__VXWORKS__) || defined(__vxworks))
        #define NCAOL_SPECS_OS_DEF_OS_SUBJECT NCAOL_SPECS_OS_VAL_SUBJECT_Other
        #define NCAOL_SPECS_OS_DEF_OS_DOMAIN  NCAOL_SPECS_OS_VAL_DOMAIN_Other
        #define NCAOL_SPECS_OS_DEF_OS_NAME    NCAOL_SPECS_OS_VAL_NAME_VxWorks
        #define NCAOL_SPECS_OS_DEF_OS_ID      NCAOL_SPECS_OS_VAL_ID_VxWorks
    #endif
#elif (NCAOL_SPECS_CSTDLIB_DEF_LIB_ID == NCAOL_SPECS_CSTDLIB_VAL_ID_klibc)
#elif (NCAOL_SPECS_CSTDLIB_DEF_LIB_ID == NCAOL_SPECS_CSTDLIB_VAL_ID_uClibc)
#elif (NCAOL_SPECS_CSTDLIB_DEF_LIB_ID == NCAOL_SPECS_CSTDLIB_VAL_ID_zOSlib)
#elif (NCAOL_SPECS_CSTDLIB_DEF_LIB_ID == NCAOL_SPECS_CSTDLIB_VAL_ID_WINDOWS)
#endif

#if defined(NCAOL_SPECS_OS_DEF_OS_ID)
    #if (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_AIX)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_Android)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_Amdahl_UTS)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_AmigaOS)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_Apollo_AEGIS)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_Apollo_DomainOS)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_BeOS)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_BlueGene)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_BSD_Environment)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_BSD_OS)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_ConvexOS)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_Cygwin_Environment)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_DG_UX)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_DragonFly)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_DYNIX_ptx)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_eCos)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_EMX_Environment)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_FreeBSD)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_GNU_Hurd)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_GNU_kFreeBSD)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_GNU_Linux)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_HIUX_MPP)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_HPUX)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_IBM_OS400)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_INTEGRITY)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_Interix_Environment)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_IRIX)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_Linux_kernel)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_LynxOS)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_MacOS_9)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_MacOS_X)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_Microware_OS9)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_MINIX)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_MorphOS)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_MPE_iX)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_MSDOS)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_NetBSD)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_NonStop)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_NucleusRTOS)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_OpenBSD)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_OS2)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_PalmOS)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_Plan9)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_Pyramid_DCOSx)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_QNX)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_Reliant_UNIX)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_SCO_OpenServer)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_Solaris)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_Stratus_VOS)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_SVR4_Environment)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_Syllable)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_SymbianOS)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_Tru64_OSF1)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_Ultrix)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_UNICOS)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_UNICOS_mp)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_UNIX_Environment)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_UnixWare)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_UWin_Environment)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_OpenVMS)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_VxWorks)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_Windows)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_Windows_CE)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_WindU_Environment)
    #elif (NCAOL_SPECS_OS_DEF_OS_ID == NCAOL_SPECS_OS_VAL_ID_zOS)
    #endif
#else
    #error "nCAOL: Apologizes, but it seems like the utilized Operating System is unsupported! - But please do feel free to send a request, if you have the spare time."
#endif


#endif