#ifndef NIGMA_CAOL_STANDILICS_H
#define NIGMA_CAOL_STANDILICS_H

/*Architecture-Specific identifications:
C89(K&R)/C90(ANSI-C):
    __STDC__
        [UNDEFINED]
C94/C95:
    __STDC_VERSION__
        199409L
C99:
    __STDC_VERSION__
        199901L
C11:
    __STDC_VERSION__
        201112L
C17/C18:
    __STDC_VERSION__
        201710L
C23:
    __STDC_VERSION__
        202311L
*/
#define CAOL_STANDILICS_DEF_STDID_C89C90 0
#define CAOL_STANDILICS_DEF_STDID_C94C95 1
#define CAOL_STANDILICS_DEF_STDID_C99    2
#define CAOL_STANDILICS_DEF_STDID_C11    3
#define CAOL_STANDILICS_DEF_STDID_C17C18 4
#define CAOL_STANDILICS_DEF_STDID_C23    5

#define CAOL_STANDILICS_DEF_STDNAME_C89C90 "C89(K&R) / C90(ANSI-C)"
#define CAOL_STANDILICS_DEF_STDNAME_C94C95 "C94 / C95"
#define CAOL_STANDILICS_DEF_STDNAME_C99    "C99"
#define CAOL_STANDILICS_DEF_STDNAME_C11    "C11"
#define CAOL_STANDILICS_DEF_STDNAME_C17C18 "C17 / C18"
#define CAOL_STANDILICS_DEF_STDNAME_C23    "C23"

#if defined(__STDC_VERSION__)
    #if (__STDC_VERSION__ == 199409L)
        #define CAOL_STANDILICS_DEF_STD_ID CAOL_STANDILICS_DEF_STDID_C94C95
        #define CAOL_STANDILICS_DEF_STD_NAME CAOL_STANDILICS_DEF_STDNAME_C94C95
    #elif (__STDC_VERSION__ == 199901L)
        #define CAOL_STANDILICS_DEF_STD_ID CAOL_STANDILICS_DEF_STDID_C99
        #define CAOL_STANDILICS_DEF_STD_NAME CAOL_STANDILICS_DEF_STDNAME_C99
    #elif (__STDC_VERSION__ == 201112L)
        #define CAOL_STANDILICS_DEF_STD_ID CAOL_STANDILICS_DEF_STDID_C11
        #define CAOL_STANDILICS_DEF_STD_NAME CAOL_STANDILICS_DEF_STDNAME_C11
    #elif (__STDC_VERSION__ == 201710L)
        #define CAOL_STANDILICS_DEF_STD_ID CAOL_STANDILICS_DEF_STDID_C17C18
        #define CAOL_STANDILICS_DEF_STD_NAME CAOL_STANDILICS_DEF_STDNAME_C17C18
    #elif (__STDC_VERSION__ == 202311L)
        #define CAOL_STANDILICS_DEF_STD_ID CAOL_STANDILICS_DEF_STDID_C23
        #define CAOL_STANDILICS_DEF_STD_NAME CAOL_STANDILICS_DEF_STDNAME_C23
    #else
        #error "nCAOL: Apologizes, but it seems like the utilized standard is unsupported!.."
    #endif
#else
    #if defined(__STDC__)
        #define CAOL_STANDILICS_DEF_STD_ID CAOL_STANDILICS_DEF_STDID_C89C90
        #define CAOL_STANDILICS_DEF_STD_NAME CAOL_STANDILICS_DEF_STDNAME_C89C90
    #else
        #error "nCAOL: Apologizes, but it seems like the utilized standard is unsupported! - Somehow one before C94/C95 that isn't C89(K&R)/C90(ANSI-C)?.."
    #endif
#endif

#define caolStandilics(t, ...) CAOL_STANDILICS_##t(__VA_ARGS__)
#define CAOL_STANDILICS_STD(t, ...)   CAOL_STANDILICS_STD_##t(__VA_ARGS__)
#define CAOL_STANDILICS_STD_NAME()    CAOL_STANDILICS_DEF_STD_NAME
#define CAOL_STANDILICS_STD_ID()      CAOL_STANDILICS_DEF_STD_ID

#define CAOL_STANDILICS_C89() CAOL_STANDILICS_DEF_STDID_C89C90
#define CAOL_STANDILICS_C90() CAOL_STANDILICS_DEF_STDID_C89C90
#define CAOL_STANDILICS_C94() CAOL_STANDILICS_DEF_STDID_C94C95
#define CAOL_STANDILICS_C95() CAOL_STANDILICS_DEF_STDID_C94C95
#define CAOL_STANDILICS_C99() CAOL_STANDILICS_DEF_STDID_C99
#define CAOL_STANDILICS_C11() CAOL_STANDILICS_DEF_STDID_C11
#define CAOL_STANDILICS_C17() CAOL_STANDILICS_DEF_STDID_C17C18
#define CAOL_STANDILICS_C18() CAOL_STANDILICS_DEF_STDID_C17C18
#define CAOL_STANDILICS_C23() CAOL_STANDILICS_DEF_STDID_C23
#define CAOL_STANDILICS_TOP() CAOL_STANDILICS_DEF_STDID_C23

#endif